[pytest]

addopts =
    -v
    --html=reports/report.html
    --self-contained-html
    
markers =
    smoke: pruebas críticas y rápidas
    exception: casos que validan manejo de errores
    api: pruebas de servicios de backend (API REST)
    ui: pruebas de interfaz
    e2e: pruebas end-to-end de flujos completos