name: CI TalentoLab

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      PIP_CACHE: ~/.cache/pip
      
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Cache dependencias
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Instalar Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create reports directory
        run: mkdir -p reports/screens logs

      - name: Run Pytest & Behave
        run: |
          # Ejecuta todas las carpetas de pruebas
          pytest tests/ tests_api/ tests_behave/ -v --html=reports/report.html --self-contained-html
          # Ejecuta los escenarios Gherkin de Behave
          behave

      - name: Upload HTML report and Screens
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/

      - name: Upload Suite Log
        uses: actions/upload-artifact@v4
        with:
          name: suite-log
          path: logs/